### ISSUE TITLE
Add tutorial about "Diffusion Models for Medical Anomaly Detection"

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/GenerativeModels#155]
Add tutorial and necessary components to perform the anomaly detection based on [Wolleb et al. "Diffusion Models for Medical Anomaly Detection"](https://arxiv.org/pdf/2203.04306.pdf) . Official code available at this [link](https://gitlab.com/cian.unibas.ch/diffusion-anomaly)

**Comment by farhancv09** [comment]
Thank you for the tutorial. I found out that there are different hyperparameters from paper. Such as
 1) Training iterations for model and classifier
 2) Value of S and L 
 I also found one mistake probably. 
 3) These is logical mistake in the code I guess. Healthy label are 1 while in the code it is mentioned as 0. (func=lambda x: 0.0 if x.sum() > 0 else 1.0))
 I need some suggestions as I am trying to implement this code my data. 
 4)  How much slices will be sufficient per class? As we normally have more images for healthy than cancerous.  
 5) Can we train the GAN with multimodality rather than just flair ? Like include T2w, T1W for both model and classifier?
